### ISSUE TITLE
dtbo

### ISSUE THREAD

**Issue by wode2016501** [CruelKernel/samsung-exynos9820#140]
find  -name  *.dtbo 
./arm64/boot/dts/samsung/exynos9820-beyond1lte_eur_open_22.dtbo
./arm64/boot/dts/samsung/exynos9820-beyond1lte_eur_open_20.dtbo
./arm64/boot/dts/samsung/exynos9820-beyond1lte_eur_open_26.dtbo
./arm64/boot/dts/samsung/exynos9820-beyond1lte_eur_open_17.dtbo
./arm64/boot/dts/samsung/exynos9820-beyond1lte_eur_open_24.dtbo
./arm64/boot/dts/samsung/exynos9820-beyond1lte_eur_open_21.dtbo
./arm64/boot/dts/samsung/exynos9820-beyond1lte_eur_open_23.dtbo
./arm64/boot/dts/samsung/exynos9820-beyond1lte_eur_open_19.dtbo
./arm64/boot/dts/samsung/exynos9820-beyond1lte_eur_open_18.dtbo
root@localhost:~/s10/exynos9820-beyond1lte-samsung-g973f-bsko-cruel/arch# 

问题
如何打包dtbo呢  写入入dtbo分区呢   cat 多个文件可以吗

**Comment by evdenis** [comment]
Please, use English.
