### ISSUE TITLE
没有发现beyond1.cfg在那里找到呢

### ISSUE THREAD

**Issue by wode2016501** [CruelKernel/samsung-exynos9820#160]
wode@wode-virtual-machine:~/s10/kernel/s10$ mkdtimg cfg_create hk-out/beyond1/dtbo hk-out/dtconfigs/beyond1.cfg -d arch/arm64/boot/dts/samsung
Can not open config file: hk-out/dtconfigs/beyond1.cfg

**Comment by evdenis** [comment]
Please, use English. This mkdtimg command has nothing in common with CruelKernel. There is no such config as beyond1.cfg. Use cruelbuild to build dtb/dtbo images. Use cruel/dtbo.G973F, cruel/dtb.G973F config files from this repo if you want to call mkdtimg directly.
