### ISSUE TITLE
new kernel sources?

### ISSUE THREAD

**Issue by t0rzz** [CruelKernel/samsung-exynos9820#175]
May I ask you if we have the latest kernel sources to merge with 4.4? Thank you in advance!
Also, is there an option to not specify if selinux will be permissive or enforced, and decide it via software?

Thank you

**Comment by evdenis** [comment]
What do you mean latest kernel sources? Samsung bases this kernel on v4.14 linux kernel

**Comment by evdenis** [comment]
> Also, is there an option to not specify if selinux will be permissive or enforced, and decide it via software?

It's by default. You don't need to select anything to get it.

**Comment by t0rzz** [comment]
> What do you mean latest kernel sources? Samsung bases this kernel on v4.14 linux kernel

Latest kernel is FUF3: https://opensource.samsung.com/uploadSearch?searchValue=SM-G975


> > Also, is there an option to not specify if selinux will be permissive or enforced, and decide it via software?
> 
> It's by default. You don't need to select anything to get it.

by default it’s always enforced and it can’t be modified neither by setenforce nor by any software-related app.

**Comment by evdenis** [comment]
> Latest kernel is FUF3: https://opensource.samsung.com/uploadSearch?searchValue=SM-G975

Yes, I'll add this.

> by default it’s always enforced 

by default in CruelKernel selinux mode is switchable

**Comment by t0rzz** [comment]
I dont want to open a new issue, as it would be identical to this one. Have we got the new kernel sources for FUH3? Thank you

**Comment by evdenis** [comment]
Samsung didn't publish the sources yet

**Comment by t0rzz** [comment]
I believe they released FUH3 and FUH5 already. Thank you!

**Comment by evdenis** [comment]
> I believe they released FUH3 and FUH5 already.

I imported these source more than 2 weeks ago. See cruel-FUH3-v4.6 branch.
