### ISSUE TITLE
check mass_storage and drivedroid

### ISSUE THREAD

**Issue by evdenis** [CruelKernel/samsung-exynos9820#25]
Los?
Samsung firmware?

**Comment by Andycar** [comment]
It doesn't work (N975FXXU6DTJ4 - based Dr. Ketan ROM)
also [UMS-Interface](https://github.com/outofmemo/UMS-Interface/blob/c0229033f1dd20843acd7c46ca4b0e8c41bce8bb/app/src/main/java/com/sjj/echo/umsinterface/MassStorageConfigfs.java) doesn't work

======
>mount | grep 'type configfs'
none on /config type configfs (rw,nosuid,nodev,noexec,relatime)
none on /sys/kernel/config type configfs (rw,relatime)

>find /config -name mass_storage*
[empty]
======

Maybe the function is provided by usb_f_mass_storage.ko module?
(as per [documentation](https://github.com/CruelKernel/samsung-exynos9820/blob/7a75415aa8244032d455f653cb31828e6b992df1/Documentation/usb/gadget-testing.txt) file)
Thanks!

**Comment by Andycar** [comment]
I see that 
CONFIG_USB_F_MASS_STORAGE=y
CONFIG_USB_CONFIGFS_MASS_STORAGE=y 

are configured now when we use the switch +mass_storage

However, no mass_storage* directory appears in /config at runtime.

Would it make any difference if we build this as module(s)?:

CONFIG_USB_F_MASS_STORAGE=M
CONFIG_USB_CONFIGFS_MASS_STORAGE=M

Thanks

**Comment by Andycar** [comment]
After  [this](https://github.com/Andycar/samsung-exynos9820/commit/10fda765ecb205261ad77154e2fe78980522ebed) commit, **still no mass storage functions show up** in any of those paths that DriveDroid expects:

/config/usb_gadget/g1/functions/mass_storage.0/lun.#/
/sys/devices/platform/usb_mass_storage/lun#/
/sys/class/android_usb/android#/f_mass_storage/lun/
/sys/devices/virtual/android_usb/android#/f_mass_storage/lun_ex/
/sys/devices/virtual/android_usb/android#/f_mass_storage/lun/
/sys/devices/virtual/android_usb/android0/f_mass_storage/lun#/
