### ISSUE TITLE
adopt patches

### ISSUE THREAD

**Issue by evdenis** [CruelKernel/samsung-exynos9820#31]
Look at how these patches could be adopted:
1) Kernel/sched: Reduce latency for better responsiveness  https://github.com/CruelKernel/samsung-exynos9820/pull/26/commits/c750d2808059524e345454dceedac4612d7f915a
2) mm: Decrease swappiness to 8  https://github.com/CruelKernel/samsung-exynos9820/pull/26/commits/9948bf19066087cb9f48dc140eb47a466a5a9d65
3) "block: set readahead to 512 " https://github.com/CruelKernel/samsung-exynos9820/pull/26/commits/df5ce7966348f535aea1165145dfc91fc11c7c01 or "mm: set 2048KB as default" https://github.com/CruelKernel/samsung-exynos9820/pull/26/commits/2e0285ba7d59cb6b61b13aed61bc8fe5be78cd6f
4) "fs:dcache Reduce vfs cache pressure to 50 " https://github.com/CruelKernel/samsung-exynos9820/pull/26/commits/573e9b95f60fe1eb6eebdbaade4dadfc442d94b8
5) "drivers/mmc/core- Add better CRC control " https://github.com/CruelKernel/samsung-exynos9820/pull/26/commits/e1e637cca730cb3ddb8ad5cee151eac4de8a1245

**Comment by evdenis** [comment]
https://github.com/UpInTheAir/Samsung-Galaxy-Tab-S-Kernel-MM/commit/2d3a085bde642706db602f7ed976e47930c62c09

**Comment by evdenis** [comment]
https://patchwork.kernel.org/project/linux-block/patch/20201207121245.50529-1-rsalvaterra@gmail.com/

**Comment by extremegrief1** [comment]
Swappiness decreasing not needed, I just realized I had it commited by mistake. Same with th readahead and vfs.
