### ISSUE TITLE
Add wireguard updater script

### ISSUE THREAD

**Issue by evdenis** [CruelKernel/samsung-exynos9820#40]

**Comment by ghost** [comment]
https://github.com/ananjaser1211/Helios_7870/blob/100b0d2603e247b14dc04adb1c0174be3f4ffaf4/scripts/fetch-latest-wireguard.sh

**Comment by ghost** [comment]
https://github.com/ananjaser1211/Helios_7870/commit/d1e62123a617c043ea2fddb3042bc22aad6ba7da

https://github.com/ananjaser1211/Helios_7870/commit/100b0d2603e247b14dc04adb1c0174be3f4ffaf4

This adds wireguard support. It downloads it whenever you build it. Might need some things modified for your build script with configs and such.

**Comment by ghost** [comment]
I commited in my fork, you can check.
